name: mulmuger
packages:
  - .

scripts:
  dev:
    run: flutter run --flavor dev -t lib/main_dev.dart
  widgetbook:
    run: flutter run -d macos -t lib/widgetbook/widgetbook.dart
  watch:
    run: melos exec -- flutter pub run build_runner watch -d
