name: widgetbook_workspace
publish_to: "none"

environment:
  sdk: ^3.8.0

dependencies:
  flutter_lints:
  widgetbook_annotation: ^3.5.0
  widgetbook: ^3.14.1
  mulmuger:
    path: ../

dev_dependencies:
  build_runner:
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true
