name: Widgetbook Cloud Hosting
on:
  push:
    branches: ["main"]

jobs:
  widgetbook-cloud-hosting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Bootstrap App # 프로젝트 루트에서 실행 (pubspec.yaml 있는 곳)
        run: |
          flutter pub get
          dart run build_runner build -d

      - name: Build Widgetbook # 프로젝트 루트에서 실행 (빌드 명령어에 lib/widgetbook/widgetbook.dart 경로 명시)
        run: |
          flutter build web -t lib/widgetbook/widgetbook.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Push Widgetbook Build
        id: push_widgetbook
        run: |
          BUILD_OUTPUT=$(widgetbook cloud build push --api-key ${{ secrets.WIDGETBOOK_API_KEY }})
          BUILD_URL=$(echo "$BUILD_OUTPUT" | grep -oE 'https://app.widgetbook.io/[0-9a-fA-F\-]+/[0-9a-fA-F\-]+/builds/[0-9a-fA-F\-]+')
          echo "build_url=$BUILD_URL" >> "$GITHUB_OUTPUT"

      - name: Add Widgetbook URL to Pull Request Comment
        if: success() && github.event_name == 'push' && steps.push_widgetbook.outputs.build_url != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✨ **Widgetbook Cloud Preview Available!** ✨

            최신 빌드는 다음 링크에서 확인할 수 있습니다: ${{ steps.push_widgetbook.outputs.build_url }}

            _이 댓글은 푸시할 때마다 최신 빌드 링크로 자동 업데이트됩니다._
          update-tag: widgetbook-cloud-preview-link
